version: '3.7'

services:
  ncore:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ncore-postgres-data:/var/lib/postgresql/ncore
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: ncore

volumes:
  ncore-postgres-data:
